<?php

declare(strict_types=1);

namespace App\Http\Resources;

use App\Models\ProductMedia;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * @mixin ProductMedia
 */
final class PublicProductMediaResource extends JsonResource
{
    /**
     * Transform processed product media into a customer-safe response.
     *
     * The original uploaded file is intentionally not returned. Public clients
     * should use optimized WebP renditions generated by the media-processing
     * queue.
     *
     * @return array<string, mixed>
     */
    public function toArray(
        Request $request
    ): array {
        return [
            'public_id' =>
                (string) $this->public_id,

            'media_type' =>
                $this->mediaTypeValue(),

            'alt_text' =>
                $this->alt_text,

            'is_primary' =>
                (bool) $this->is_primary,

            'sort_order' =>
                (int) $this->sort_order,

            'variant_public_id' =>
                $this->when(
                    $this->relationLoaded(
                        'variant'
                    ),
                    fn (): ?string =>
                        $this->variant !== null
                            ? (string) $this
                                ->variant
                                ->public_id
                            : null
                ),

            /*
            |--------------------------------------------------------------------------
            | Preferred image
            |--------------------------------------------------------------------------
            |
            | Product-list cards should use this URL directly.
            |
            */

            'url' =>
                $this->cardUrl(),

            /*
            |--------------------------------------------------------------------------
            | Optimized public URLs
            |--------------------------------------------------------------------------
            |
            | No original-upload URL is exposed here.
            |
            */

            'urls' => [
                'thumbnail' =>
                    $this->thumbnailUrl(),

                'card' =>
                    $this->cardUrl(),

                'detail' =>
                    $this->detailUrl(),

                'original_optimized' =>
                    $this->originalOptimizedUrl(),
            ],

            /*
            |--------------------------------------------------------------------------
            | Optimized rendition metadata
            |--------------------------------------------------------------------------
            */

            'renditions' => [
                'thumbnail' =>
                    $this->publicRendition(
                        ProductMedia
                            ::RENDITION_THUMBNAIL
                    ),

                'card' =>
                    $this->publicRendition(
                        ProductMedia
                            ::RENDITION_CARD
                    ),

                'detail' =>
                    $this->publicRendition(
                        ProductMedia
                            ::RENDITION_DETAIL
                    ),

                'original_optimized' =>
                    $this->publicRendition(
                        ProductMedia
                            ::RENDITION_ORIGINAL_OPTIMIZED
                    ),
            ],
        ];
    }

    /**
     * Return the preferred thumbnail URL.
     */
    private function thumbnailUrl(): ?string
    {
        return $this->firstOptimizedUrl([
            ProductMedia
                ::RENDITION_THUMBNAIL,

            ProductMedia
                ::RENDITION_CARD,

            ProductMedia
                ::RENDITION_DETAIL,

            ProductMedia
                ::RENDITION_ORIGINAL_OPTIMIZED,
        ]);
    }

    /**
     * Return the preferred product-card URL.
     *
     * The original upload is never used as a fallback.
     */
    private function cardUrl(): ?string
    {
        return $this->firstOptimizedUrl([
            ProductMedia
                ::RENDITION_CARD,

            ProductMedia
                ::RENDITION_DETAIL,

            ProductMedia
                ::RENDITION_THUMBNAIL,

            ProductMedia
                ::RENDITION_ORIGINAL_OPTIMIZED,
        ]);
    }

    /**
     * Return the preferred product-detail URL.
     */
    private function detailUrl(): ?string
    {
        return $this->firstOptimizedUrl([
            ProductMedia
                ::RENDITION_DETAIL,

            ProductMedia
                ::RENDITION_ORIGINAL_OPTIMIZED,

            ProductMedia
                ::RENDITION_CARD,

            ProductMedia
                ::RENDITION_THUMBNAIL,
        ]);
    }

    /**
     * Return the optimized-original URL.
     *
     * A detail rendition may be used when optimized-original processing did
     * not generate a usable file.
     */
    private function originalOptimizedUrl(): ?string
    {
        return $this->firstOptimizedUrl([
            ProductMedia
                ::RENDITION_ORIGINAL_OPTIMIZED,

            ProductMedia
                ::RENDITION_DETAIL,

            ProductMedia
                ::RENDITION_CARD,
        ]);
    }

    /**
     * Select the first available optimized rendition.
     *
     * @param array<int, string> $renditionNames
     */
    private function firstOptimizedUrl(
        array $renditionNames
    ): ?string {
        if (!$this->isCompleted()) {
            return null;
        }

        foreach (
            $renditionNames
            as $renditionName
        ) {
            $url =
                $this->renditionUrl(
                    $renditionName
                );

            if (
                is_string($url)
                && trim($url) !== ''
            ) {
                return trim($url);
            }
        }

        /*
         * Never fall back to originalUrl() in a public response.
         */

        return null;
    }

    /**
     * Return customer-safe metadata for one optimized rendition.
     *
     * Internal storage disk and path values are deliberately excluded.
     *
     * @return array<string, mixed>|null
     */
    private function publicRendition(
        string $name
    ): ?array {
        if (!$this->isCompleted()) {
            return null;
        }

        $rendition =
            $this->rendition($name);

        if ($rendition === null) {
            return null;
        }

        $url =
            $this->renditionUrl($name);

        if (
            !is_string($url)
            || trim($url) === ''
        ) {
            return null;
        }

        return [
            'url' =>
                trim($url),

            'width' =>
                isset(
                    $rendition['width']
                )
                && is_numeric(
                    $rendition['width']
                )
                    ? (int) $rendition[
                        'width'
                    ]
                    : null,

            'height' =>
                isset(
                    $rendition['height']
                )
                && is_numeric(
                    $rendition['height']
                )
                    ? (int) $rendition[
                        'height'
                    ]
                    : null,

            'size_bytes' =>
                isset(
                    $rendition[
                        'size_bytes'
                    ]
                )
                && is_numeric(
                    $rendition[
                        'size_bytes'
                    ]
                )
                    ? (int) $rendition[
                        'size_bytes'
                    ]
                    : null,

            'mime_type' =>
                isset(
                    $rendition[
                        'mime_type'
                    ]
                )
                    ? (string) $rendition[
                        'mime_type'
                    ]
                    : 'image/webp',
        ];
    }
}
