<?php

declare(strict_types=1);

namespace App\OpenApi;

use OpenApi\Attributes as OA;

#[OA\Info(
    version: '1.0.0',
    title: 'RushPi Marketplace API',
    description: 'REST API documentation for the RushPi verified electronics marketplace.',
    contact: new OA\Contact(
        name: 'RushPi Backend Team'
    )
)]
#[OA\Server(
    url: 'https://rushpi.asyncafrica.com/api/v1',
    description: 'RushPi production API'
)]
#[OA\SecurityScheme(
    securityScheme: 'sanctum',
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'Bearer Token',
    description: 'Enter the authentication token generated by the login endpoint.'
)]
#[OA\Tag(
    name: 'System',
    description: 'Application health and infrastructure checks.'
)]
#[OA\Tag(
    name: 'Authentication',
    description: 'User registration, login, logout and profile authentication.'
)]
#[OA\Tag(
    name: 'Seller Profiles',
    description: 'Seller profile management endpoints.'
)]
#[OA\Schema(
    schema: 'ValidationError',
    type: 'object',
    properties: [
        new OA\Property(
            property: 'success',
            type: 'boolean',
            example: false
        ),
        new OA\Property(
            property: 'message',
            type: 'string',
            example: 'Validation failed.'
        ),
        new OA\Property(
            property: 'errors',
            type: 'object',
            example: [
                'email' => [
                    'The email field is required.',
                ],
            ]
        ),
    ]
)]
#[OA\Schema(
    schema: 'UnauthenticatedError',
    type: 'object',
    properties: [
        new OA\Property(
            property: 'message',
            type: 'string',
            example: 'Unauthenticated.'
        ),
    ]
)]
final class OpenApiSpec
{
}
